app = "solosuccess-n8n-config"
primary_region = "atl"

[build]
  image = "n8nio/n8n:latest"

  [http_service]
    internal_port = 5678
      force_https = true
        auto_stop_machines = false
          auto_start_machines = true
            min_machines_running = 1

            [[vm]]
              cpu_kind = "shared"
                cpus = 1
                  memory_mb = 256

                  [mounts]
                    source="n8n_data"
                      destination="/home/node/.n8n"
                      app = "solosuccess-n8n-config"
                      primary_region = "atl"

                      [build]
                        image = "n8nio/n8n:latest"

                        [http_service]
                          internal_port = 5678
                            force_https = true
                              auto_stop_machines = false
                                auto_start_machines = true
                                  min_machines_running = 1

                                  [[vm]]
                                    cpu_kind = "shared"
                                      cpus = 1
                                        memory_mb = 256

                                        [mounts]
                                          source="n8n_data"
                                            destination="/home/node/.n8n"
                                            app = "solosuccess-n8n-config"
                                            primary_region = "atl"

                                            [build]
                                              image = "n8nio/n8n:latest"

                                              [http_service]
                                                internal_port = 5678
                                                  force_https = true
                                                    auto_stop_machines = false
                                                      auto_start_machines = true
                                                        min_machines_running = 1

                                                        [[vm]]
                                                          cpu_kind = "shared"
                                                            cpus = 1
                                                              memory_mb = 256

                                                              [mounts]
                                                                source="n8n_data"
                                                                  destination="/home/node/.n8n"
                                                                  