# fly.toml app configuration file generated for solosuccess-n8n-config on 2025-09-13T13:23:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'solosuccess-n8n-config'
primary_region = 'iad'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
